### ISSUE TITLE
Printing manual

### ISSUE THREAD

**Issue by suegrimmond** [Urban-Meteorology-Reading/UMEP-Docs#15]
For testing the SUEWS tutorial - I converted the manual to PDF -- as I am going to be offline.
All of the figures etc are going off the edge of the page.

**Comment by sunt05** [comment]
This can be resolved by setting `width: 80%` along those figures overflowing beyond the page edges. Sorry I just fixed those for `SUEWS_Spatial` as I'm about to leave. But this workaround should resolve other places as well.
