### ISSUE TITLE
add caption

### ISSUE THREAD

**Issue by tyhzxc** [Urban-Meteorology-Reading/UMEP-Docs#8]
chapter_________________fig number
3.3_________________3.5 3.7
3.4_________________3.18
3.5_________________ 3.20 3.21 3.22
3.7_________________ 3.24
3.8_________________ 3.25
3.9_________________3.27 3.28
3.10_________________3.29 3.30
3.11_________________3.31
3.12_________________3.32
3.13_________________3.33 3.34
3.14_________________3.35
3.15_________________3.36                          
4.2_________________ 4.5
4.3_________________4.7 4.8
4.4_________________4.9 4.10
4.5_________________4.11
4.7_________________4.12
4.8_________________4.13
5.2_________________5.3
5.3_________________5.4
5.4 _________________5.5
10 _________________10.1

tutorials part
4 caption  in footprint
2 caption in SUEWS_advanced
4 caption in SEBE
13 caption in LQF
6 caption in GQF
5 caption in IntroductionToSuews

**Comment by biglimp** [comment]
Fixed.
